receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:

exporters:
  otlp/quickwit:
    endpoint: quickwit:7281
    tls:
      insecure: true

  prometheusremotewrite:
    endpoint: "http://thanos-receiver:10908/api/v1/receive"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/quickwit]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite]
