name: CI
on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release-please
        with:
          release-type: rust
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
      tag_name: ${{ steps.release-please.outputs.tag_name }}

  publish-artifacts:
    needs: release
    if: ${{ needs.release.outputs.release_created }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: login to dockerhub
        uses: "docker/login-action@v2"
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push image
        run: |
          ./scripts/dockerbuild.sh defenxor/dsiem-rs push
      - name: extract binaries
        uses: shrink/actions-docker-extract@v3
        with:
          image: defenxor/dsiem-rs:latest
          path: /dsiem/.
          destination: dsiem
      - name: zip binaries
        run: |
          rm -rf dsiem/configs && mv dsiem/configs-dist dsiem/configs
          cp LICENSE dsiem/LICENSE
          cp README.md dsiem/README.md
          zip -9 -r dsiem-server_linux_x86_64.zip dsiem
          sha256sum dsiem-server_linux_x86_64.zip > dsiem-server_linux_x86_64.zip.sha256.txt
      - name: upload release artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ needs.release.outputs.tag_name }} dsiem-server_linux_x86_64.zip
          gh release upload ${{ needs.release.outputs.tag_name }} dsiem-server_linux_x86_64.zip.sha256.txt
